name: Print Software Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  PrintLanguageVersions:
    name: Data Processing Level - Application Server / Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Java Version
        run: java --version

      - name: Print Node.js Version
        run: node --version

      - name: Print Python Version
        run: python3 --version

  PrintDBMSVersions:
    name: Data Access Level - PostgreSQL Database
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print PostgreSQL Version
        run: psql --version
