# https://github.com/marketplace/actions/super-linter
name: Program Code Convention Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ProgramCodeLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v4

      - name: Lint Java Program Code
        uses: github/super-linter@v4
        env:
          VALIDATE_JAVA: true
          FILTER_REGEX_INCLUDE: .*/.*\.java
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

